"""User and Userdatabse Relationship

Revision ID: d74e3a65c908
Revises: 
Create Date: 2024-11-29 12:10:57.491155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74e3a65c908'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('database', sa.String(), nullable=False))
    op.create_foreign_key(None, 'users', 'user_databases', ['database'], ['db_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'database')
    # ### end Alembic commands ###
